name: Run Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v3
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - name: Run Gosec Security Scanner
        uses: informalsystems/gosec@master
        with:
          args: ./...
        if: "env.GIT_DIFF != ''"
